### ISSUE TITLE
GoG data file incorrect

### ISSUE THREAD

**Issue by petteyg** [arx/ArxGentoo#3]
Currently, the files available from GoG to download are for a version 1.22, not 2.0.0.7 as this ebuild asks.

3281bebe8c816c8abadb8e2989e061fd0992a103a52655e5f6edd7a0dd0029f7dfc8be6f08c78b5f26526d34c5493929266e8b6258faac388ee11faa5810acf4  /home/petteyg/Downloads/setup_arx_fatalis_1.22_(38577)-1.bin
3f79b812e7b478bdfeb66ad35b2127351204ed64ec9b6a9c7608b6ec33c0411f46f64f63f816e592a4a7831527c3a99bd60d1153a6fe0138a52dfe7722e3075b  /home/petteyg/Downloads/setup_arx_fatalis_1.22_(38577).exe

**Comment by dscharrer** [comment]
Thanks for the reminder, this please let me know if games-rpg/arx-fatalis-data-1.22.38577 still does not work for you.
